// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
   static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiBQP74iC_c06XqsVAIWcg2RQLb0k8s3I', 
    appId: '1:307031613459:web:eaff304b6a3ab3772a9fe6', 
    messagingSenderId: '307031613459', 
    projectId: 'pi3-rpg', 
    authDomain: '://firebaseapp.com', 
    storageBucket: 'pi3-rpg.firebasestorage.app', 
    databaseURL: 'https://pi3-rpg-default-rtdb.firebaseio.com/', 
    measurementId: 'G-5CLYCEYP1M', 
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4d9ZSHgkYPQaWscrFTm9_tBrapv-HOcw',
    appId: '1:420337132658:android:a2b0cf9f4beede6b1c0eeb',
    messagingSenderId: '420337132658',
    projectId: 'projeto-integrador-iii-2ff26',
    storageBucket: 'projeto-integrador-iii-2ff26.firebasestorage.app',
    authDomain: '://firebaseapp.com',
    databaseURL: 'https://projeto-integrador-iii-2ff26-default-rtdb.firebaseio.com/',

  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgKnhaDuR1GeEhqDZk6LRU-2f7QiU36IY',
    appId: '1:420337132658:ios:c801e0f2b0220e9b1c0eeb',
    messagingSenderId: '420337132658',
    projectId: 'projeto-integrador-iii-2ff26',
    storageBucket: 'projeto-integrador-iii-2ff26.firebasestorage.app',
    iosBundleId: 'com.example.piIiiRpgInterativo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgKnhaDuR1GeEhqDZk6LRU-2f7QiU36IY',
    appId: '1:420337132658:ios:c801e0f2b0220e9b1c0eeb',
    messagingSenderId: '420337132658',
    projectId: 'projeto-integrador-iii-2ff26',
    storageBucket: 'projeto-integrador-iii-2ff26.firebasestorage.app',
    iosBundleId: 'com.example.piIiiRpgInterativo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0JvsShHzMmpJ9m7wn-HpqLEJepGu3KAA',
    appId: '1:420337132658:web:817ddfaef4bd35ec1c0eeb',
    messagingSenderId: '420337132658',
    projectId: 'projeto-integrador-iii-2ff26',
    authDomain: '://firebaseapp.com',
    databaseURL: 'https://projeto-integrador-iii-2ff26-default-rtdb.firebaseio.com/',
    storageBucket: 'projeto-integrador-iii-2ff26.firebasestorage.app',
    measurementId: 'G-L382KT0GYK',
  );
}
